### ISSUE TITLE
Type error trying to pipe(tap) mutator observable

### ISSUE THREAD

**Issue by IanIsFluent** [timdeschryver/rx-query#16] opened 2020-12-10 12:46 UTC
I am trying to clear a different cache when a mutation completes.

I was under the impression that `pipe(tap({complete: () => refreshQuery('tags-all'}))` wouldn't change the original Observable (its called transparent in the RxJS docs). But it seems to change the type, such that I get this error when trying to use it on a mutator function with data type `string[]`: 

```
Type 'Observable<string[] | "RX_QUERY_NOOP_MUTATE">' is not assignable to type 'string[] | Observable<string[]> | "RX_QUERY_NOOP_MUTATE" | Observable<"RX_QUERY_NOOP_MUTATE">'.
  Type 'Observable<string[] | "RX_QUERY_NOOP_MUTATE">' is not assignable to type 'Observable<string[]>'.
    Type 'string[] | "RX_QUERY_NOOP_MUTATE"' is not assignable to type 'string[]'.
      Type 'string' is not assignable to type 'string[]'.ts(2322)
```

If I had wanted to tap the 'next' function, then as long as I tell it the parameter type, I don't get any type errors:
`tap((_: string[]) => refreshQuery('tags-all'))` works

**Comment by timdeschryver** [comment] 2020-12-13 15:39
That's strange that shouldn't happen, or this is something that has to be fixed in the RxJS repo.
Do you have a reproduction, because I'm not able to reproduce this.

**Comment by IanIsFluent** [comment] 2020-12-14 07:09
Totally agree it shouldn't happen! It shouldn't even affect the typings, right?! As its using `tap`! Um, I guess easiest repo is to start with an Angular Stackblitz, right? (this is for a work project, so can't easily get you all the source...)

**Comment by timdeschryver** [comment] 2020-12-14 18:58
Creating a stackblitz is probably the fastest/easiest.
I tried using the [example in this repo](https://github.com/timdeschryver/rx-query/tree/master/src/examples) but as I said, I'm not able to reproduce it.

**Comment by IanIsFluent** [comment] 2020-12-15 08:26
> Creating a stackblitz is probably the fastest/easiest.
> I tried using the [example in this repo](https://github.com/timdeschryver/rx-query/tree/master/src/examples) but as I said, I'm not able to reproduce it.

OK. not sure when I'll have time to do it. It certainly happened here - but maybe a verison issue?

```
    "@angular/core": "9.1.12",
    "typescript": "3.8.3",
    "rxjs": "^6.6.3",
```

**Closed** 2021-07-22 16:03 UTC
Labels: needs reproduction
